[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DA2DP_I2S_AUDIOTOOLS=0
lib_deps =
  https://github.com/pschatzmann/ESP32-A2DP.git#v.1.8.2
